### PR TITLE
added .editorconfig #9

### LINKED ISSUE #9: Add editorconfig at this project
Adding [editorconfig](https://editorconfig.org/) at this project some rules will be preserved.

Maybe will can be create like this:

````editorconfig
root = true

[*]
indent_style = space
indent_size = 2
end_of_line = crlf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true
````

The `editorconfig` have compatibility with various editors/IDEs and similars. This can be see [here](https://editorconfig.org/).

### PR DESCRIPTION
**Pull request by tadeubdev**
Close #9 - Add defaults in .editorconfig file
  - Change indentation to spaces
  - Change indentation size to 2
  - Ignore some directories:
    - system/**
    - aplication/{cache,config,libraries}/**

Correct indentation in same files
  - Correct indentation in files from application/controllers, application/views and another files when is not from the system.

### CODE REVIEW

**Comment by rahgurung** [comment]
Hey, @tadeubarbosa I added StyleCI for this project, and I think this is no longer needed in the repo. Thanks for the PR.

**Comment by tadeubdev** [comment]
Ok, @gurrrung! 
You're welcome!

**Comment by rahgurung** [comment]
@tadeubarbosa now project follows the standard style in all files, but I am studying styleci I think adding a .styleci.yml would be the next task.

**Comment by tadeubdev** [comment]
I did not know the styleci, I will learn now.
I like it!

**Pull request closed without merging**
